// Package abi loads the Strimz contract ABIs (extracted from `forge build`)
// and exposes a typed event-decoder API for the indexer's projector layer.
//
// ABI source-of-truth: ABI JSON files committed in this directory, embedded
// into the binary via `//go:embed`. Regenerated by `make abi` whenever the
// contracts change. Loading at startup means a malformed ABI (e.g., a typo
// in a field name after a contract change) fails the binary at boot rather
// than at the first matching event.
package abi

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"math/big"
	"strings"

	ethabi "github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

//go:embed *.abi.json
var abiFS embed.FS

// EventName is the canonical event name (matches Solidity declaration).
type EventName string

const (
	// Registry
	EventMerchantRegistered           EventName = "MerchantRegistered"
	EventMerchantPayoutAddressUpdated EventName = "MerchantPayoutAddressUpdated"
	EventMerchantFeeBpsUpdated        EventName = "MerchantFeeBpsUpdated"
	EventMerchantActiveSet            EventName = "MerchantActiveSet"
	EventMerchantOwnerTransferred     EventName = "MerchantOwnerTransferred"

	// Payments (one-shot)
	EventPaymentExecuted EventName = "PaymentExecuted"

	// Subscriptions
	EventSubscriptionCreated       EventName = "SubscriptionCreated"
	EventSubscriptionCharged       EventName = "SubscriptionCharged"
	EventSubscriptionChargeSkipped EventName = "SubscriptionChargeSkipped"
	EventSubscriptionCancelled     EventName = "SubscriptionCancelled"

	// Agent escrow
	EventJobCreated   EventName = "JobCreated"
	EventJobFunded    EventName = "JobFunded"
	EventJobStarted   EventName = "JobStarted"
	EventJobDelivered EventName = "JobDelivered"
	EventJobApproved  EventName = "JobApproved"
	EventJobReleased  EventName = "JobReleased"
	EventJobDisputed  EventName = "JobDisputed"
	EventJobCancelled EventName = "JobCancelled"
	EventJobRefunded  EventName = "JobRefunded"
	// Terminal exits added when the escrow gained a dispute-resolution
	// and timeout-reclaim path. Without these the indexer leaves any
	// disputed or abandoned job parked in a non-terminal status forever.
	EventJobResolved  EventName = "JobResolved"
	EventJobReclaimed EventName = "JobReclaimed"

	// Fees
	EventFeeAccrued EventName = "FeeAccrued"

	// ERC-20 (used only for refund-completion detection)
	EventERC20Transfer EventName = "Transfer"
)

// SubscribedEvents is the exhaustive set the projector handles. Anything not
// in this list with a matching topic[0] is decoded but logged-and-skipped.
var SubscribedEvents = []EventName{
	EventMerchantRegistered, EventMerchantPayoutAddressUpdated, EventMerchantFeeBpsUpdated,
	EventMerchantActiveSet, EventMerchantOwnerTransferred,
	EventPaymentExecuted,
	EventSubscriptionCreated, EventSubscriptionCharged, EventSubscriptionChargeSkipped, EventSubscriptionCancelled,
	EventJobCreated, EventJobFunded, EventJobStarted, EventJobDelivered,
	EventJobApproved, EventJobReleased, EventJobDisputed, EventJobCancelled,
	EventJobRefunded, EventJobResolved, EventJobReclaimed,
	EventFeeAccrued,
	EventERC20Transfer,
}

// Registry holds parsed ABIs and a topic-to-event lookup table.
type Registry struct {
	abis      map[string]ethabi.ABI // contract name → parsed ABI
	byTopic   map[common.Hash]boundEvent
	allTopics []common.Hash
}

type boundEvent struct {
	contract string
	event    ethabi.Event
}

// MustLoad loads the embedded ABIs. Panics on a malformed ABI — that's a
// build-time mistake, not a runtime condition.
func MustLoad() *Registry {
	r, err := Load()
	if err != nil {
		panic(err)
	}
	return r
}

// Load parses every embedded `*.abi.json` and returns a populated Registry.
func Load() (*Registry, error) {
	entries, err := abiFS.ReadDir(".")
	if err != nil {
		return nil, fmt.Errorf("read embedded abi: %w", err)
	}

	r := &Registry{
		abis:    make(map[string]ethabi.ABI),
		byTopic: make(map[common.Hash]boundEvent),
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".abi.json") {
			continue
		}
		data, err := abiFS.ReadFile(entry.Name())
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", entry.Name(), err)
		}
		parsed, err := ethabi.JSON(bytes.NewReader(data))
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", entry.Name(), err)
		}
		contractName := strings.TrimSuffix(entry.Name(), ".abi.json")
		r.abis[contractName] = parsed
		for _, ev := range parsed.Events {
			// Topic[0] = event ID. Multiple contracts can declare ERC-20
			// `Transfer` etc.; first registration wins, later ones share the
			// same decoder so we don't error on duplicates.
			if _, exists := r.byTopic[ev.ID]; exists {
				continue
			}
			r.byTopic[ev.ID] = boundEvent{contract: contractName, event: ev}
			r.allTopics = append(r.allTopics, ev.ID)
		}
	}
	return r, nil
}

// AllTopics returns every event topic[0] in the registry. Used to build the
// `eth_getLogs` filter so the RPC node only returns logs we can decode.
func (r *Registry) AllTopics() []common.Hash {
	out := make([]common.Hash, len(r.allTopics))
	copy(out, r.allTopics)
	return out
}

// SubscribedTopics returns the topic[0] values for `SubscribedEvents`,
// keeping the filter narrow to events the projector actually projects.
func (r *Registry) SubscribedTopics() []common.Hash {
	out := make([]common.Hash, 0, len(SubscribedEvents))
	seen := make(map[common.Hash]struct{}, len(SubscribedEvents))
	for _, name := range SubscribedEvents {
		topic, ok := r.TopicByName(name)
		if !ok {
			continue // contract change in flight; defensive
		}
		if _, dup := seen[topic]; dup {
			continue
		}
		seen[topic] = struct{}{}
		out = append(out, topic)
	}
	return out
}

// TopicByName looks up an event's topic[0] across all loaded ABIs.
func (r *Registry) TopicByName(name EventName) (common.Hash, bool) {
	for _, parsed := range r.abis {
		if ev, ok := parsed.Events[string(name)]; ok {
			return ev.ID, true
		}
	}
	return common.Hash{}, false
}

// Decode parses a raw `types.Log` into one of the typed payload structs in
// this file, using the registry to find the right contract+event by topic[0].
//
// Returns:
//   - `(name, payload, nil)` on a successful decode
//   - `("", nil, nil)`        when topic[0] is not one we own (caller skips)
//   - `(name, nil, err)`      on a malformed log for an event we own
func (r *Registry) Decode(log types.Log) (EventName, interface{}, error) {
	if len(log.Topics) == 0 {
		return "", nil, errors.New("log has no topics")
	}
	bound, ok := r.byTopic[log.Topics[0]]
	if !ok {
		return "", nil, nil
	}
	parsed := r.abis[bound.contract]

	values := make(map[string]interface{}, len(bound.event.Inputs))
	if err := parsed.UnpackIntoMap(values, bound.event.Name, log.Data); err != nil {
		return EventName(bound.event.Name), nil, fmt.Errorf("unpack data: %w", err)
	}
	if err := ethabi.ParseTopicsIntoMap(values, indexedArgs(bound.event), log.Topics[1:]); err != nil {
		return EventName(bound.event.Name), nil, fmt.Errorf("unpack topics: %w", err)
	}

	payload, err := materialise(EventName(bound.event.Name), values)
	if err != nil {
		return EventName(bound.event.Name), nil, err
	}
	return EventName(bound.event.Name), payload, nil
}

func indexedArgs(ev ethabi.Event) ethabi.Arguments {
	var indexed ethabi.Arguments
	for _, arg := range ev.Inputs {
		if arg.Indexed {
			indexed = append(indexed, arg)
		}
	}
	return indexed
}

// ----- Typed payloads -----
//
// One struct per event. Field names match the ABI argument names (exported
// in Go). Big numbers are `*big.Int`; addresses are `common.Address`;
// bytes32 is `[32]byte`.

type MerchantRegistered struct {
	MerchantID    *big.Int
	Owner         common.Address
	PayoutAddress common.Address
	FeeBps        uint16
}

type MerchantPayoutAddressUpdated struct {
	MerchantID       *big.Int
	NewPayoutAddress common.Address
}

type MerchantFeeBpsUpdated struct {
	MerchantID *big.Int
	NewFeeBps  uint16
}

type MerchantActiveSet struct {
	MerchantID *big.Int
	Active     bool
}

type MerchantOwnerTransferred struct {
	MerchantID *big.Int
	NewOwner   common.Address
}

type PaymentExecuted struct {
	MerchantID *big.Int
	Payer      common.Address
	Token      common.Address
	Amount     *big.Int
	FeeAmount  *big.Int
	NetAmount  *big.Int
	Ref        [32]byte
}

type SubscriptionCreated struct {
	SubscriptionID *big.Int
	MerchantID     *big.Int
	Payer          common.Address
	Token          common.Address
	Amount         *big.Int
	IntervalSecs   uint32
	StartAt        uint64
}

type SubscriptionCharged struct {
	SubscriptionID  *big.Int
	ChargeAttemptID [32]byte
	Amount          *big.Int
	FeeAmount       *big.Int
	NetAmount       *big.Int
	NextChargeAt    uint64
}

// ChargeOutcome mirrors the on-chain enum in IStrimzSubscriptions.sol.
// Order is frozen: new outcomes append, never insert.
//
//	0  None              never emitted; guards uninitialised slots
//	1  Charged
//	2  InsufficientFunds
//	3  RevokedApproval
//	4  Cancelled
//	5  NotDue
//	6  Ended             past endAt
//	7  Duplicate         chargeAttemptId already spent
//	8  Unknown           subscriptionId never existed
//	9  MerchantInactive  merchant frozen/unknown at charge time
//	10 TransferFailed    token transfer reverted mid-charge
type ChargeOutcome uint8

const (
	ChargeOutcomeNone              ChargeOutcome = 0
	ChargeOutcomeCharged           ChargeOutcome = 1
	ChargeOutcomeInsufficientFunds ChargeOutcome = 2
	ChargeOutcomeRevokedApproval   ChargeOutcome = 3
	ChargeOutcomeCancelled         ChargeOutcome = 4
	ChargeOutcomeNotDue            ChargeOutcome = 5
	ChargeOutcomeEnded             ChargeOutcome = 6
	ChargeOutcomeDuplicate         ChargeOutcome = 7
	ChargeOutcomeUnknown           ChargeOutcome = 8
	ChargeOutcomeMerchantInactive  ChargeOutcome = 9
	ChargeOutcomeTransferFailed    ChargeOutcome = 10
)

// String returns the DB enum value (`SubscriptionChargeOutcome`) for the
// outcome — used directly in SQL.
func (c ChargeOutcome) DBString() string {
	switch c {
	case ChargeOutcomeCharged:
		return "charged"
	case ChargeOutcomeInsufficientFunds:
		return "insufficient_funds"
	case ChargeOutcomeRevokedApproval:
		return "revoked_approval"
	case ChargeOutcomeCancelled:
		return "cancelled"
	case ChargeOutcomeNotDue:
		return "not_due"
	case ChargeOutcomeEnded:
		return "ended"
	case ChargeOutcomeDuplicate:
		return "duplicate"
	case ChargeOutcomeUnknown:
		return "unknown"
	case ChargeOutcomeMerchantInactive:
		return "merchant_inactive"
	case ChargeOutcomeTransferFailed:
		return "transfer_failed"
	default:
		// ChargeOutcomeNone and anything a future contract appends.
		return "skipped"
	}
}

// IsPaymentFailure reports whether the outcome means "we tried to bill
// this payer and could not" — as opposed to "there was nothing to bill".
//
// Only these outcomes should move a subscription to `at_risk` and arm the
// retry backoff. A NotDue from an early sweep, or a Duplicate from the
// indexer lagging a confirmed charge, are scheduler noise: treating them
// as failures downgrades a healthy payer on the merchant dashboard and
// pushes out their next retry for no reason.
func (c ChargeOutcome) IsPaymentFailure() bool {
	switch c {
	case ChargeOutcomeInsufficientFunds,
		ChargeOutcomeRevokedApproval,
		ChargeOutcomeMerchantInactive,
		ChargeOutcomeTransferFailed:
		return true
	default:
		return false
	}
}

type SubscriptionChargeSkipped struct {
	SubscriptionID  *big.Int
	ChargeAttemptID [32]byte
	Outcome         ChargeOutcome
}

type SubscriptionCancelled struct {
	SubscriptionID *big.Int
	By             common.Address
}

type JobCreated struct {
	JobID  *big.Int
	Client common.Address
	Vendor common.Address
	Token  common.Address
	Amount *big.Int
}

type JobFunded struct {
	JobID  *big.Int
	Amount *big.Int
}

type JobStarted struct {
	JobID *big.Int
}

type JobDelivered struct {
	JobID           *big.Int
	DeliverableHash [32]byte
}

type JobApproved struct {
	JobID    *big.Int
	Assessor common.Address
}

type JobReleased struct {
	JobID  *big.Int
	Vendor common.Address
	Amount *big.Int
}

type JobDisputed struct {
	JobID  *big.Int
	By     common.Address
	Reason string
}

type JobCancelled struct {
	JobID  *big.Int
	Reason string
}

type JobRefunded struct {
	JobID  *big.Int
	To     common.Address
	Amount *big.Int
}

type JobResolved struct {
	JobID    *big.Int
	Resolver common.Address
	ToVendor *big.Int
	ToClient *big.Int
}

// FromStatus is the JobStatus the job held when the timeout fired, so the
// projector can report what was abandoned (Funded / InProgress /
// Delivered / Disputed) rather than just "reclaimed".
type JobReclaimed struct {
	JobID      *big.Int
	To         common.Address
	Amount     *big.Int
	FromStatus uint8
}

type FeeAccrued struct {
	Token      common.Address
	MerchantID *big.Int
	Amount     *big.Int
}

type ERC20Transfer struct {
	From  common.Address
	To    common.Address
	Value *big.Int
}

// materialise converts the `(name, args-by-name)` map produced by
// go-ethereum's ABI unpacker into one of the typed structs above.
//
// Solidity argument names use camelCase by convention (verified by reading
// the `*.sol` interfaces). Any future contract change that renames a field
// will fail this lookup loudly — exactly what we want.
func materialise(name EventName, v map[string]interface{}) (interface{}, error) {
	get := func(k string) interface{} { return v[k] }

	bigint := func(k string) (*big.Int, error) {
		x, ok := get(k).(*big.Int)
		if !ok {
			return nil, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	addr := func(k string) (common.Address, error) {
		x, ok := get(k).(common.Address)
		if !ok {
			return common.Address{}, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	u16 := func(k string) (uint16, error) {
		x, ok := get(k).(uint16)
		if !ok {
			return 0, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	u32 := func(k string) (uint32, error) {
		x, ok := get(k).(uint32)
		if !ok {
			return 0, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	u64 := func(k string) (uint64, error) {
		x, ok := get(k).(uint64)
		if !ok {
			return 0, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	u8 := func(k string) (uint8, error) {
		x, ok := get(k).(uint8)
		if !ok {
			return 0, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	boolVal := func(k string) (bool, error) {
		x, ok := get(k).(bool)
		if !ok {
			return false, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	str := func(k string) (string, error) {
		x, ok := get(k).(string)
		if !ok {
			return "", fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}
	b32 := func(k string) ([32]byte, error) {
		x, ok := get(k).([32]byte)
		if !ok {
			return [32]byte{}, fmt.Errorf("%s.%s missing or wrong type", name, k)
		}
		return x, nil
	}

	switch name {
	case EventMerchantRegistered:
		merchantID, e1 := bigint("merchantId")
		owner, e2 := addr("owner")
		payout, e3 := addr("payoutAddress")
		feeBps, e4 := u16("feeBps")
		if err := firstErr(e1, e2, e3, e4); err != nil {
			return nil, err
		}
		return &MerchantRegistered{MerchantID: merchantID, Owner: owner, PayoutAddress: payout, FeeBps: feeBps}, nil

	case EventMerchantPayoutAddressUpdated:
		merchantID, e1 := bigint("merchantId")
		payout, e2 := addr("newPayoutAddress")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &MerchantPayoutAddressUpdated{MerchantID: merchantID, NewPayoutAddress: payout}, nil

	case EventMerchantFeeBpsUpdated:
		merchantID, e1 := bigint("merchantId")
		fee, e2 := u16("newFeeBps")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &MerchantFeeBpsUpdated{MerchantID: merchantID, NewFeeBps: fee}, nil

	case EventMerchantActiveSet:
		merchantID, e1 := bigint("merchantId")
		active, e2 := boolVal("active")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &MerchantActiveSet{MerchantID: merchantID, Active: active}, nil

	case EventMerchantOwnerTransferred:
		merchantID, e1 := bigint("merchantId")
		owner, e2 := addr("newOwner")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &MerchantOwnerTransferred{MerchantID: merchantID, NewOwner: owner}, nil

	case EventPaymentExecuted:
		merchantID, e1 := bigint("merchantId")
		payer, e2 := addr("payer")
		token, e3 := addr("token")
		amount, e4 := bigint("amount")
		feeAmount, e5 := bigint("feeAmount")
		netAmount, e6 := bigint("netAmount")
		ref, e7 := b32("ref")
		if err := firstErr(e1, e2, e3, e4, e5, e6, e7); err != nil {
			return nil, err
		}
		return &PaymentExecuted{
			MerchantID: merchantID, Payer: payer, Token: token,
			Amount: amount, FeeAmount: feeAmount, NetAmount: netAmount, Ref: ref,
		}, nil

	case EventSubscriptionCreated:
		subID, e1 := bigint("subscriptionId")
		merchantID, e2 := bigint("merchantId")
		payer, e3 := addr("payer")
		token, e4 := addr("token")
		amount, e5 := bigint("amount")
		interval, e6 := u32("interval")
		startAt, e7 := u64("startAt")
		if err := firstErr(e1, e2, e3, e4, e5, e6, e7); err != nil {
			return nil, err
		}
		return &SubscriptionCreated{
			SubscriptionID: subID, MerchantID: merchantID, Payer: payer, Token: token,
			Amount: amount, IntervalSecs: interval, StartAt: startAt,
		}, nil

	case EventSubscriptionCharged:
		subID, e1 := bigint("subscriptionId")
		attempt, e2 := b32("chargeAttemptId")
		amount, e3 := bigint("amount")
		fee, e4 := bigint("feeAmount")
		net, e5 := bigint("netAmount")
		next, e6 := u64("nextChargeAt")
		if err := firstErr(e1, e2, e3, e4, e5, e6); err != nil {
			return nil, err
		}
		return &SubscriptionCharged{
			SubscriptionID: subID, ChargeAttemptID: attempt,
			Amount: amount, FeeAmount: fee, NetAmount: net, NextChargeAt: next,
		}, nil

	case EventSubscriptionChargeSkipped:
		subID, e1 := bigint("subscriptionId")
		attempt, e2 := b32("chargeAttemptId")
		outcome, e3 := u8("outcome")
		if err := firstErr(e1, e2, e3); err != nil {
			return nil, err
		}
		return &SubscriptionChargeSkipped{
			SubscriptionID: subID, ChargeAttemptID: attempt, Outcome: ChargeOutcome(outcome),
		}, nil

	case EventSubscriptionCancelled:
		subID, e1 := bigint("subscriptionId")
		by, e2 := addr("by")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &SubscriptionCancelled{SubscriptionID: subID, By: by}, nil

	case EventJobCreated:
		jobID, e1 := bigint("jobId")
		client, e2 := addr("client")
		vendor, e3 := addr("vendor")
		token, e4 := addr("token")
		amount, e5 := bigint("amount")
		if err := firstErr(e1, e2, e3, e4, e5); err != nil {
			return nil, err
		}
		return &JobCreated{JobID: jobID, Client: client, Vendor: vendor, Token: token, Amount: amount}, nil

	case EventJobFunded:
		jobID, e1 := bigint("jobId")
		amount, e2 := bigint("amount")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &JobFunded{JobID: jobID, Amount: amount}, nil

	case EventJobStarted:
		jobID, err := bigint("jobId")
		if err != nil {
			return nil, err
		}
		return &JobStarted{JobID: jobID}, nil

	case EventJobDelivered:
		jobID, e1 := bigint("jobId")
		hash, e2 := b32("deliverableHash")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &JobDelivered{JobID: jobID, DeliverableHash: hash}, nil

	case EventJobApproved:
		jobID, e1 := bigint("jobId")
		assessor, e2 := addr("assessor")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &JobApproved{JobID: jobID, Assessor: assessor}, nil

	case EventJobReleased:
		jobID, e1 := bigint("jobId")
		vendor, e2 := addr("vendor")
		amount, e3 := bigint("amount")
		if err := firstErr(e1, e2, e3); err != nil {
			return nil, err
		}
		return &JobReleased{JobID: jobID, Vendor: vendor, Amount: amount}, nil

	case EventJobDisputed:
		jobID, e1 := bigint("jobId")
		by, e2 := addr("by")
		reason, e3 := str("reason")
		if err := firstErr(e1, e2, e3); err != nil {
			return nil, err
		}
		return &JobDisputed{JobID: jobID, By: by, Reason: reason}, nil

	case EventJobRefunded:
		jobID, e1 := bigint("jobId")
		to, e2 := addr("to")
		amount, e3 := bigint("amount")
		if err := firstErr(e1, e2, e3); err != nil {
			return nil, err
		}
		return &JobRefunded{JobID: jobID, To: to, Amount: amount}, nil

	case EventJobResolved:
		jobID, e1 := bigint("jobId")
		resolver, e2 := addr("resolver")
		toVendor, e3 := bigint("toVendor")
		toClient, e4 := bigint("toClient")
		if err := firstErr(e1, e2, e3, e4); err != nil {
			return nil, err
		}
		return &JobResolved{JobID: jobID, Resolver: resolver, ToVendor: toVendor, ToClient: toClient}, nil

	case EventJobReclaimed:
		jobID, e1 := bigint("jobId")
		to, e2 := addr("to")
		amount, e3 := bigint("amount")
		fromStatus, e4 := u8("fromStatus")
		if err := firstErr(e1, e2, e3, e4); err != nil {
			return nil, err
		}
		return &JobReclaimed{JobID: jobID, To: to, Amount: amount, FromStatus: fromStatus}, nil

	case EventJobCancelled:
		jobID, e1 := bigint("jobId")
		reason, e2 := str("reason")
		if err := firstErr(e1, e2); err != nil {
			return nil, err
		}
		return &JobCancelled{JobID: jobID, Reason: reason}, nil

	case EventFeeAccrued:
		token, e1 := addr("token")
		merchantID, e2 := bigint("merchantId")
		amount, e3 := bigint("amount")
		if err := firstErr(e1, e2, e3); err != nil {
			return nil, err
		}
		return &FeeAccrued{Token: token, MerchantID: merchantID, Amount: amount}, nil

	case EventERC20Transfer:
		from, e1 := addr("from")
		to, e2 := addr("to")
		value, e3 := bigint("value")
		if err := firstErr(e1, e2, e3); err != nil {
			return nil, err
		}
		return &ERC20Transfer{From: from, To: to, Value: value}, nil

	default:
		return nil, fmt.Errorf("no materialiser for event %q", name)
	}
}

func firstErr(errs ...error) error {
	for _, e := range errs {
		if e != nil {
			return e
		}
	}
	return nil
}
