import { render } from '@react-email/components'
import type { ReactElement } from 'react'

/**
 * Render a React Email template to a single HTML string ready to hand
 * to Resend (or any SMTP transport).
 *
 * `pretty: false` shrinks the wire size by ~30% — irrelevant for
 * deliverability but keeps logs and Resend dashboards readable.
 *
 * Plain-text fallbacks are NOT auto-generated by React Email yet; if a
 * future template needs one, render again with `plainText: true` from
 * @react-email/render and ship both.
 */
export async function renderToHtml(element: ReactElement): Promise<string> {
  return render(element, { pretty: false })
}
