/**
 * The `@/.source` import resolves to a folder generated by `fumadocs-mdx`
 * during `next dev` / `next build`. This stub keeps `tsc` happy before the
 * first build runs; the runtime import always resolves at build time.
 */
declare module '@/.source' {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const docs: any
}
