import type { Metadata } from 'next'
import { LegalDoc } from '@/components/marketing/legal-doc'
import { OG_IMAGE } from '@/lib/seo'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Strimz Terms of Service — the agreement between Strimz and merchants using the platform.',
  alternates: { canonical: '/legal/terms' },
  openGraph: { title: 'Terms of Service · Strimz', url: '/legal/terms', images: [OG_IMAGE] },
}

const TOC = [
  { id: 'agreement', label: '1. Agreement to Terms' },
  { id: 'service', label: '2. The Service' },
  { id: 'accounts', label: '3. Accounts' },
  { id: 'fees', label: '4. Fees' },
  { id: 'on-chain', label: '5. On-chain settlement' },
  { id: 'acceptable-use', label: '6. Acceptable use' },
  { id: 'data', label: '7. Data + privacy' },
  { id: 'ip', label: '8. Intellectual property' },
  { id: 'warranty', label: '9. Warranties + disclaimer' },
  { id: 'liability', label: '10. Limitation of liability' },
  { id: 'termination', label: '11. Termination' },
  { id: 'changes', label: '12. Changes to terms' },
  { id: 'law', label: '13. Governing law' },
]

export default function TermsPage() {
  return (
    <LegalDoc
      title="Terms of Service"
      description="The agreement between you and Strimz Labs Ltd. governing your use of strimz.finance and the Strimz API."
      effectiveDate="1 May 2026"
      lastUpdated="1 May 2026"
      toc={TOC}
    >
      <h2 id="agreement">1. Agreement to Terms</h2>
      <p>
        These Terms of Service ("Terms") form a binding agreement between you and Strimz Labs Ltd.
        ("Strimz", "we", "us") governing your access to and use of the Strimz website, dashboard,
        APIs, SDKs, hosted checkout, and developer documentation (collectively, the "Service"). By
        creating an account, calling the API, or otherwise using the Service, you confirm that you
        have read these Terms and agree to be bound by them. If you are entering into these Terms on
        behalf of a company, you represent that you have authority to bind that entity, and "you"
        means that entity.
      </p>
      <p>If you do not agree to these Terms, do not use the Service.</p>

      <h2 id="service">2. The Service</h2>
      <p>
        Strimz provides infrastructure for accepting, managing, and settling stablecoin payments on
        the Arc blockchain ("Arc"). The Service includes a hosted dashboard, server-side and browser
        SDKs, smart contracts that you may interact with directly or through the Service, and
        webhook delivery for events generated by your account.
      </p>
      <p>
        We are not a custodian of your funds. Settlements flow directly to the wallet address you
        configure as your payout address. We never hold customer or merchant private keys, and the
        Service cannot move your funds without an on-chain transaction signed by you or an
        authorised key you control.
      </p>

      <h2 id="accounts">3. Accounts</h2>
      <p>
        To access the Service you must create an account via Privy (our identity provider). You are
        responsible for safeguarding your account credentials, including any embedded wallets Privy
        creates on your behalf. You must use a current and complete email address; we will rely on
        the address on file for legal notices, security alerts, and product communications.
      </p>
      <p>
        Live mode unlocks once you have completed: (a) email verification through Privy; (b)
        two-factor authentication enrolment; and (c) the business onboarding form (legal name,
        sector, country, payout address). You are responsible for keeping this information accurate
        and up to date.
      </p>

      <h2 id="fees">4. Fees</h2>
      <p>
        Strimz charges a per-transaction fee on every payment processed through the Service at the
        rate associated with your active plan. Fees are deducted on-chain at settlement time and
        recorded in the on-chain fee ledger maintained by the FeeCollector contract. Your dashboard
        surfaces gross volume, fees, and net amounts for every transaction.
      </p>
      <p>
        We may revise our fee schedule with at least thirty (30) days' notice via email and an
        in-dashboard banner. New fees apply only to transactions created after the effective date.
      </p>

      <h2 id="on-chain">5. On-chain settlement</h2>
      <p>You acknowledge that the Service operates on a public blockchain and that:</p>
      <ul>
        <li>On-chain transactions are public, immutable, and may be observed by third parties.</li>
        <li>
          Network conditions, gas costs (paid in USDC on Arc), and protocol upgrades are outside our
          control. We make commercially reasonable efforts to maintain uptime, but the Service is
          subject to chain-level availability.
        </li>
        <li>
          Smart contracts may contain bugs. While the Strimz contracts are audited and open source,
          we do not warrant that the contracts are free of all defects.
        </li>
      </ul>

      <h2 id="acceptable-use">6. Acceptable use</h2>
      <p>
        Your use of the Service must comply with our{' '}
        <a href="/legal/acceptable-use">Acceptable Use Policy</a> and all applicable laws, including
        sanctions, anti-money-laundering, counter-terrorism financing, and consumer protection
        regimes in your jurisdiction. You are solely responsible for the legality of the goods or
        services you sell using the Service.
      </p>

      <h2 id="data">7. Data + privacy</h2>
      <p>
        Our handling of personal data is described in the{' '}
        <a href="/legal/privacy">Privacy Policy</a>. By using the Service you consent to the
        processing described there. You retain ownership of customer data you upload or that the
        Service indexes from on-chain events on your behalf; we act as a processor for that data.
      </p>

      <h2 id="ip">8. Intellectual property</h2>
      <p>
        The Strimz name, logo, marketing site, dashboard UI, hosted checkout, and documentation are
        the intellectual property of Strimz Labs Ltd. The Strimz open-source code (smart contracts,
        SDKs, indexer, scheduler, agent, web application) is licensed separately under the MIT
        License and any contributions to those repositories are governed by their respective
        contribution guidelines.
      </p>

      <h2 id="warranty">9. Warranties + disclaimer</h2>
      <p>
        EXCEPT AS EXPRESSLY PROVIDED IN A WRITTEN AGREEMENT WITH STRIMZ, THE SERVICE IS PROVIDED "AS
        IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING
        IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
        AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING. STRIMZ DOES NOT WARRANT THAT THE
        SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.
      </p>

      <h2 id="liability">10. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL STRIMZ, ITS OFFICERS, EMPLOYEES, OR
        AGENTS BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY
        DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, OR DATA, ARISING OUT OF OR IN
        CONNECTION WITH THE SERVICE. STRIMZ'S AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF THESE
        TERMS WILL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY YOU TO STRIMZ IN THE TWELVE
        MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED US
        DOLLARS (USD 100).
      </p>

      <h2 id="termination">11. Termination</h2>
      <p>
        Either party may terminate these Terms at any time. You may close your account from the
        dashboard's Settings → Danger zone. We may suspend or terminate your account if you breach
        these Terms, our Acceptable Use Policy, or applicable law. Upon termination, your access to
        the dashboard ends, your API keys are revoked, and your webhook endpoints stop receiving
        events. Funds settled to your payout wallet remain in your control on-chain.
      </p>

      <h2 id="changes">12. Changes to terms</h2>
      <p>
        We may update these Terms from time to time. Material changes will be communicated via email
        and an in-dashboard banner at least fourteen (14) days before they take effect. Continued
        use of the Service after the effective date constitutes acceptance of the updated Terms.
      </p>

      <h2 id="law">13. Governing law</h2>
      <p>
        These Terms are governed by the laws of England and Wales. Any dispute arising out of or in
        connection with these Terms is subject to the exclusive jurisdiction of the courts of
        London, United Kingdom, except that either party may seek injunctive relief in any competent
        court to protect its intellectual property rights.
      </p>
    </LegalDoc>
  )
}
