'use client'

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Invoice } from '@/data/invoices'
import { formatUsdc } from '@/data/_seed'

/**
 * Generate and download a branded invoice PDF for a single invoice row.
 * Uses jspdf + jspdf-autotable for the line-items table.
 */
export function downloadInvoicePdf(
  invoice: Invoice,
  merchant = { name: 'Strimz Merchant', address: '' },
): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const margin = 48
  const accent: [number, number, number] = [2, 199, 106]

  // Letterhead
  doc.setFillColor(...accent)
  doc.rect(margin, margin, 16, 16, 'F')
  doc.setFontSize(22).setFont('helvetica', 'bold').setTextColor(20, 20, 30)
  doc.text(merchant.name, margin + 26, margin + 14)

  doc.setFontSize(28).setTextColor(40, 40, 60)
  doc.text('Invoice', 547, margin + 14, { align: 'right' })
  doc.setFontSize(10).setFont('helvetica', 'normal').setTextColor(110, 110, 130)
  doc.text(`#${invoice.number}`, 547, margin + 32, { align: 'right' })

  // Bill to / dates
  doc.setFontSize(9).setTextColor(120, 120, 140)
  doc.text('BILL TO', margin, margin + 70)
  doc.text('INVOICE DATE', 320, margin + 70)
  doc.text('DUE DATE', 460, margin + 70)

  doc.setFontSize(11).setTextColor(20, 20, 30)
  const billLines = [
    invoice.customerCompany ?? invoice.customerName,
    invoice.customerCompany ? invoice.customerName : '',
    invoice.customerEmail,
    invoice.customerWallet,
  ].filter(Boolean) as string[]
  billLines.forEach((line, i) => doc.text(line, margin, margin + 88 + i * 14))

  doc.text(new Date(invoice.createdAt).toLocaleDateString(), 320, margin + 88)
  doc.text(new Date(invoice.dueAt).toLocaleDateString(), 460, margin + 88)

  // Line items
  autoTable(doc, {
    startY: margin + 170,
    margin: { left: margin, right: margin },
    head: [['Description', 'Qty', 'Unit price (USDC)', 'Amount']],
    body: invoice.lineItems.map((li) => [
      li.description,
      String(li.quantity),
      formatUsdc(li.unitAmountUsdc),
      formatUsdc(li.unitAmountUsdc * li.quantity),
    ]),
    headStyles: {
      fillColor: [248, 248, 250],
      textColor: [80, 80, 100],
      fontStyle: 'bold',
      cellPadding: 8,
    },
    bodyStyles: { textColor: [40, 40, 60], cellPadding: 8 },
    columnStyles: {
      1: { halign: 'right', cellWidth: 40 },
      2: { halign: 'right', cellWidth: 110 },
      3: { halign: 'right', cellWidth: 90 },
    },
  })

  // Totals
  const finalY =
    (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? margin + 200
  const totalsX = 460
  doc.setFontSize(10).setTextColor(120, 120, 140)
  doc.text('Subtotal', 380, finalY + 24)
  doc.text('Total due', 380, finalY + 50)

  doc.setFontSize(11).setTextColor(20, 20, 30)
  doc.text(`${formatUsdc(invoice.subtotalUsdc)} USDC`, totalsX + 80, finalY + 24, {
    align: 'right',
  })

  doc.setFontSize(14).setFont('helvetica', 'bold')
  doc.text(`${formatUsdc(invoice.totalUsdc)} USDC`, totalsX + 80, finalY + 50, { align: 'right' })

  // Note + footer
  if (invoice.note) {
    doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(110, 110, 130)
    doc.text('Note', margin, finalY + 90)
    doc.setFontSize(10).setTextColor(60, 60, 80)
    doc.text(invoice.note, margin, finalY + 106)
  }

  doc.setFontSize(8).setTextColor(150, 150, 170)
  doc.text(`Generated by Strimz · ${new Date().toLocaleString()} · ${invoice.id}`, margin, 800)

  doc.save(`invoice-${invoice.number}.pdf`)
}
